# Generated by Django 3.2.13 on 2022-06-25 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20220621_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Snack', 'Snack'), ('Dessert', 'Dessert'), ('Drink', 'Drink'), ('Other', 'Other')], default='Breakfast', max_length=30),
        ),
    ]
