# Generated by Django 3.2.13 on 2022-07-06 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20220705_2359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='titleeee',
            new_name='title',
        ),
    ]
